version: "3.8"
services:
  api-eventlogger:
    build: api-eventlogger/
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/logs
    ports:
      - "9001:5000"

  api-fbanalyze:
    build: api-fbanalyze/
    environment:
       - REDIS_HOST=redis
       - REDIS_PORT=6379
       - MONGO_URI=mongodb://mongo:27017/fb
    depends_on:
      - redis
      - mongo
    ports:
      - "9002:5000"

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  redis:
  mongo:
